from litex_boards.official.platforms import arty
from litex_boards.official.platforms import avalanche
from litex_boards.official.platforms import de0nano
from litex_boards.official.platforms import genesys2
from litex_boards.official.platforms import kc705
from litex_boards.official.platforms import kcu105
from litex_boards.official.platforms import machxo3
from litex_boards.official.platforms import minispartan6
from litex_boards.official.platforms import nexys4ddr
from litex_boards.official.platforms import nexys_video
from litex_boards.official.platforms import versa_ecp3
from litex_boards.official.platforms import versa_ecp5
