from litex_boards.partner.platforms import aller
from litex_boards.partner.platforms import fomu_evt
from litex_boards.partner.platforms import fomu_hacker
from litex_boards.partner.platforms import fomu_pvt
from litex_boards.partner.platforms import nereid
from litex_boards.partner.platforms import netv2
from litex_boards.partner.platforms import tagus
from litex_boards.partner.platforms import tinyfpga_bx
from litex_boards.partner.platforms import trellisboard
from litex_boards.partner.platforms import ulx3s
